### ISSUE TITLE
NPE when calling com.google.cloud.bigquery.BigQuery.getTable(...)

### ISSUE THREAD

**Issue by mtagle** [GoogleCloudPlatform/gcloud-java#1131]
Relevant part of the exception:

```java.lang.NullPointerException
    at com.google.cloud.bigquery.StandardTableDefinition$StreamingBuffer.fromPb(StandardTableDefinition.java:113)
    at com.google.cloud.bigquery.StandardTableDefinition$Builder.<init>(StandardTableDefinition.java:147)
    at com.google.cloud.bigquery.StandardTableDefinition$Builder.<init>(StandardTableDefinition.java:119)
    at com.google.cloud.bigquery.StandardTableDefinition.fromPb(StandardTableDefinition.java:283)
    at com.google.cloud.bigquery.TableDefinition.fromPb(TableDefinition.java:172)
    at com.google.cloud.bigquery.TableInfo$BuilderImpl.<init>(TableInfo.java:157)
    at com.google.cloud.bigquery.Table.fromPb(Table.java:348)
    at com.google.cloud.bigquery.BigQueryImpl.getTable(BigQueryImpl.java:353)
```

We suspect this is happening because the table we are trying to get seems to have a streaming buffer that is empty. Here is what some of the table info looks like:

```
...
 "numBytes": "85168232",
 "numLongTermBytes": "0",
 "numRows": "144534",
 "creationTime": "1468884348851",
 "lastModifiedTime": "1469135551174",
 "type": "TABLE",
 "location": "US",
 "streamingBuffer": {
  "estimatedRows": "0",
  "estimatedBytes": "0"
 }
```

From all the documentation it looks like this maybe isn't supposed to happen at all. But, it seems to be happening here, and resulting in an NPE.

**Comment by criccomini** [comment]
At this point, we believe the issue is caused when `streamingBufferPb.getOldestEntryTime()` comes back `null`. We have a table where this is the case. See the UI below:

<img width="360" alt="screen_shot_2016-07-26_at_6 30 10_pm_720" src="https://cloud.githubusercontent.com/assets/167569/17183192/5a2b1a76-53db-11e6-9b88-69b1d1efe7b7.png">

**Comment by mziccard** [comment]
@mtagle @criccomini Thanks for the report and sorry for the latency, I will get into this ASAP and keep you posted.

**Comment by mziccard** [comment]
@mtagle @criccomini FYI `gcloud-java 0.2.7` is now out and fixes this issue
