### ISSUE TITLE
Error from storage.delete( bucket, blob)

### ISSUE THREAD

**Issue by simon-temple** [GoogleCloudPlatform/gcloud-java#175]
I'm calling:
```java
storage.delete( "my-bucket", "6c7a1892629811e5b40202420adc0211.itm" )
```
"my-bucket" exists in zone EU and the blob "6c7a1892629811e5b40202420adc0211.itm" exists in this bucket.
I can delete this blob using the Developers Console.
MyClass.java created the bucket and blob shortly before the delete() was called.

Am I doing something wrong?

```
Caused by: com.google.gcloud.RetryHelper$NonRetriableException: com.google.gcloud.storage.StorageException: 
	at com.google.gcloud.RetryHelper.doRetry(RetryHelper.java:193)
	at com.google.gcloud.RetryHelper.runWithRetries(RetryHelper.java:247)
	at com.google.gcloud.RetryHelper.runWithRetries(RetryHelper.java:237)
	at com.google.gcloud.storage.StorageImpl.delete(StorageImpl.java:313)
	at com.mycode(MyClass.java:150)\n"}
	... 5 more
Caused by: com.google.gcloud.storage.StorageException: \
	at com.google.gcloud.spi.DefaultStorageRpc.translate(DefaultStorageRpc.java:104)
	at com.google.gcloud.spi.DefaultStorageRpc.translate(DefaultStorageRpc.java:93)
	at com.google.gcloud.spi.DefaultStorageRpc.delete(DefaultStorageRpc.java:270)
	at com.google.gcloud.storage.StorageImpl$13.call(StorageImpl.java:316)\
	at com.google.gcloud.storage.StorageImpl$13.call(StorageImpl.java:313)
	at com.google.gcloud.RetryHelper.doRetry(RetryHelper.java:181)
	... 9 more\n"}
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 412 
	
	  \"code\" : 412,
	"  \"errors\" : [ {
	    \"domain\" : \"global\",
	    \"location\" : \"If-Match\",
	    \"locationType\" : \"header\",
	   \"message\" : \"\",
	    \"reason\" : \"conditionNotMet\"
	  } ],
	  \"message\" : \"\"
	
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.gcloud.spi.DefaultStorageRpc.delete(DefaultStorageRpc.java:267)
	.. 12 more
```

**Comment by mziccard** [comment]
Again, thanks for the much appreciated feedback. You are doing nothing wrong. This is an issue on our side, I'll fix it and try to merge as soon as possible. I'll keep you posted.
