### ISSUE TITLE
DatastoreOptions.defaultInstance().service() fails in static methods.

### ISSUE THREAD

**Issue by unitydynamics** [GoogleCloudPlatform/gcloud-java#721]
```
com.google.gcloud.datastore.DatastoreException: I/O error
	at com.google.gcloud.spi.DefaultDatastoreRpc.translate(DefaultDatastoreRpc.java:110)
	at com.google.gcloud.spi.DefaultDatastoreRpc.lookup(DefaultDatastoreRpc.java:147)
	at com.google.gcloud.datastore.DatastoreOptions.normalize(DatastoreOptions.java:128)
	at com.google.gcloud.datastore.DatastoreOptions.access$400(DatastoreOptions.java:36)
	at com.google.gcloud.datastore.DatastoreOptions$Builder.build(DatastoreOptions.java:89)
	at com.google.gcloud.datastore.DatastoreOptions.defaultInstance(DatastoreOptions.java:175)
	at com.industryopenings.seeker.driver.Driver.main(Driver.java:97)
Caused by: com.google.api.services.datastore.client.DatastoreException: I/O error
	at com.google.api.services.datastore.client.RemoteRpc.makeException(RemoteRpc.java:115)
	at com.google.api.services.datastore.client.RemoteRpc.call(RemoteRpc.java:83)
	at com.google.api.services.datastore.client.BaseDatastoreFactory$RemoteRpc.call(BaseDatastoreFactory.java:41)
	at com.google.api.services.datastore.client.Datastore.lookup(Datastore.java:93)
	at com.google.gcloud.spi.DefaultDatastoreRpc.lookup(DefaultDatastoreRpc.java:145)
	... 5 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.google.auth.oauth2.UserCredentials.refreshAccessToken(UserCredentials.java:121)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:97)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:74)
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:65)
	at com.google.gcloud.ServiceOptions$1.initialize(ServiceOptions.java:533)
	at com.google.api.services.datastore.client.RemoteRpc.call(RemoteRpc.java:76)
	... 8 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 29 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 35 more
```

Dropping `DatastoreOptions.defaultInstance().service()` into a simple main() method will yield the error.  I'm on 0.1.4.  Inside class instance methods it's working fine.  I'm running outside of App Engine.

**Comment by unitydynamics** [comment]
Sorry I've got an issue on my machine where multiple libraries are using the same authentication path.  As I pin this one down further I may repost.
